### PR TITLE
Add GPL-3 License

### PR DESCRIPTION
**Pull request by jmaspons**
As per CRAN policies, license can't be part of the package but can stay at the repository

### CODE REVIEW

**Comment by jmaspons** [comment]
We have a little mess here. If you like the license, I will merge the first commit of this pull request to master and investigate the extra changes in the license branch.

**Comment by stineb** [comment]
Sorry for the mess. I thought I had resolved the conflict. Yes, go ahead with the license as you have it in the license branch and merge this into master.

**Comment by jmaspons** [comment]
Done 1ef6ca84157b06cd1b768ac83b03b7adab548cd9. Are there any useful changes in this branch or could we remove it?

**Comment by stineb** [comment]
You mean remove the `license` branch? Yes I guess so.

**Pull request closed without merging**
